### ISSUE TITLE
General and Structural Backend-Refactoring 

### ISSUE THREAD

**Issue by mOceanracing** [GroceryMateOst/GroceryMateCodeBase#84]
#### User Story: [^1]
- [#79 ]

[^1]: The User Story to which this Task belongs should be attached to specify the context and navigate on it.

**Comment by mOceanracing** [comment]
\timespend 3.5

**Comment by mOceanracing** [comment]
setup inMemory-db for context-testing
\timespend 2

**Comment by mOceanracing** [comment]
Write tests for ControllerBase
\timespend 1.75

**Comment by mOceanracing** [comment]
\timespend 1

**Comment by mOceanracing** [comment]
\timespend 1.5

**Comment by mOceanracing** [comment]
\timespend 0.75

**Comment by mOceanracing** [comment]
\timespend 1

**Comment by mOceanracing** [comment]
Refactoring to Repository Pattern

\timespend 5.5

**Comment by glv12** [comment]
\timespend 2

**Comment by mOceanracing** [comment]
\timespend 3

**Comment by RamonEbneter** [comment]
\timespent 1
